FROM ubuntu:16.04

# Install packages
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y software-properties-common && \
  apt-get install -y git zsh exuberant-ctags && \
  add-apt-repository ppa:jonathonf/vim && \
  apt-get update && \
  apt-get install -y vim


